language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - g++-5
    - clang-3.7
    - libstdc++-5-dev
    - libmysqlclient-dev
    - libgoogle-perftools-dev
    - libssl-dev
    - telnet
    - libexpect-perl
    - libpcre3-dev
script: ./travis.sh
env:
  - CFLAGS="-Wall -g" CXXFLAGS="-Wall -g"
