language: c
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libgoogle-perftools-dev
    - libssl-dev
    - telnet
    - libexpect-perl
script: ./travis.sh
env:
  - CFLAGS="-Wall -g" CXXFLAGS="-Wall -g"
