language: c
compiler:
  - gcc
  - clang
sudo: false
script: ./travis.sh
env:
  - CFLAGS="-Wall -g" CXXFLAGS="-Wall -g"
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libgoogle-perftools-dev
    - libssl-dev
    - telnet
