language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmysqlclient-dev libgoogle-perftools-dev libssl-dev telnet libexpect-perl
script: ./travis.sh
env:
  - CFLAGS="-Wall -g" CXXFLAGS="-Wall -g"
