language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - g++-5
    - clang-3.7
    - libstdc++-5-dev
    - libmysqlclient-dev
    - libgoogle-perftools-dev
    - libssl-dev
    - telnet
    - libexpect-perl
    - libpcre3-dev
script: ./travis.sh
env:
  - CFLAGS="-Wall -g" CXXFLAGS="-Wall -g"
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50
  - if [ ${CC} == "clang" ]; then
    export CC=/usr/bin/clang-3.7 CXX=/usr/bin/clang++-3.7;
    fi
